(define (union-set-with-ordering set1 set2)
  (cond ((null? set1) set2)
        ((null? set2) set1)
        ((= (car set1) (car set2)) (union-set-with-ordering (cdr set1) set2))
        ((< (car set1) (car set2)) (cons (car set1) (union-set-with-ordering (cdr set1) set2)))
        (else (cons (car set2) (union-set-with-ordering set1 (cdr set2))))))
